remote_theme: "mmistakes/minimal-mistakes@4.22.0"
#remote_theme: minimal-mistakes-jekyll

layout: splash

layout: single
title: false
plugins:
  - jekyll-include-cache  
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
sidebar:
  nav: "docs"

include:
  - "_pages"

search: true
